// tools/build-history.js — regenerate history.js from games-archive/.
// Each archive file holds one past week's GAMES array. Duplicates are merged
// by content hash, and anything identical to the live prompts.js is excluded
// (that is the current week, not history). Run after every Monday games drop.
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
// App files live under app/ in a fresh repo checkout, but at the local
// root on this machine. games-archive/ sits at the repo root in both.
const APP_DIR = fs.existsSync(path.join(ROOT, "app", "index.html"))
  ? path.join(ROOT, "app")
  : ROOT;
const ARCHIVE = path.join(ROOT, "games-archive");

function loadGames(src) {
  const fn = new Function(src + "\n;return (typeof GAMES !== 'undefined') ? GAMES : null;");
  return fn();
}
function hash(games) {
  return crypto.createHash("sha1").update(JSON.stringify(games)).digest("hex");
}
function weekLabel(src, filename) {
  const m = src.match(/Week of (\d{4}-\d{2}-\d{2})/);
  if (m) return m[1];
  const f = filename.match(/(\d{4}-\d{2}-\d{2})/);
  return f ? f[1] : filename.replace(/\.js$/, "");
}

const currentGames = loadGames(fs.readFileSync(path.join(APP_DIR, "prompts.js"), "utf8"));
const currentHash = hash(currentGames);

const seen = {};
fs.readdirSync(ARCHIVE)
  .filter((f) => f.endsWith(".js"))
  .sort()
  .forEach((f) => {
    const src = fs.readFileSync(path.join(ARCHIVE, f), "utf8");
    const games = loadGames(src);
    if (!games || !games.length) return;
    const h = hash(games);
    if (h === currentHash) return; // live week, not history
    if (!seen[h]) seen[h] = { week: weekLabel(src, f), games: games };
  });

const history = Object.values(seen).sort((a, b) => (a.week < b.week ? -1 : 1));
const out =
  "/* GPS Kids Daily - past weeks, auto-generated by tools/build-history.js. Do not edit by hand. */\n" +
  "var GAME_HISTORY = " +
  JSON.stringify(history, null, 2) +
  ";\n";
fs.writeFileSync(path.join(APP_DIR, "history.js"), out);
console.log("history.js written with " + history.length + " past week(s).");
